spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://67.205.163.33/sif33
    username: sif33
    password: InfSci1500_4583362
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#Mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

